accounts/urls.py
from django.urls import path
from . import views

app_name = 'user'
urlpatterns = [
    path('', views.home, name='home'),
    path('signup', views.signup_view, name='signup'),
    path('verify-email/', views.verify_email, name='verify-email'),
    path('verify-email/done/', views.verify_email_done, name='verify-email-done'),
    path('verify-email-confirm/<uidb64>/<token>/', views.verify_email_confirm, name='verify-email-confirm'),
    path('verify-email/complete/', views.verify_email_complete, name='verify-email-complete'),
]

setup/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls', namespace="user"))
]

accounts/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.base_user import BaseUserManager


class CustomUserManager(BaseUserManager):
    def create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError(_("Veuillez renseigner une adresse email"))
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user
    
    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)
        
        if extra_fields.get('is_staff') is not True:
            raise ValueError(_("Un super utilisateur doit définir is_staff=True"))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_("Un super utilisateur doit définir is_superuser=True"))
        
        return self.create_user(email, password, **extra_fields)


class CustomUser(AbstractUser):
    username = None
    email = models.EmailField(_("Adresse email"), max_length=254, unique=True)   
    email_is_verified = models.BooleanField(default=False)
    
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    
    objects = CustomUserManager()
    
    def __str__(self):
        return self.email
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)


    

accounts/forms.py
from django import forms
from django.contrib.auth import authenticate, get_user_model
from django.utils.translation import gettext_lazy as _


User = get_user_model()


class UserRegisterForm(forms.ModelForm):
    password = forms.CharField(label=_("Mot de passe"))
    
    class Meta:
        model = User
        fields = ("email", 'password')
        
    def clean(self, *args, **kwargs):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        email_check = User.objects.filter(email=email)
        if email_check.exists():
            raise forms.ValidationError(_("Cette adresse email existe déjà !"))
        if len(password) < 6:
            raise forms.ValidationError(_("Mot de passe doit comporter au moins 6 caractères !"))
    
        return super(UserRegisterForm, self).clean(*args, **kwargs)

accounts/views.py
import httpx
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.contrib import messages
from django.core.mail import EmailMessage

from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, get_user_model, login
from .forms import UserRegisterForm


User = get_user_model()


def home(request):
    BASE_URL = "https://api.ote-godaddy.com"
    headers = {'X-Shopper-Id': '1234567890'}
    endpoint = f"{BASE_URL}/v1/domains/"
    domains = httpx.get(endpoint, headers=headers)
    template_name = "accounts/home.html"
    context = {
        'name': "BOUE",
        'domains': domains,
    }
    return render(request, template_name, context)

def verify_email(request):
    if request.method == 'POST':
        if request.user.email_is_verified:
            current_site = get_current_site(request)
            user = request.user
            email = request.user.email
            subject = _("Email de vérification")
            message = render_to_string('accounts/verify-email-message.html', {
                'request': request,
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            email = EmailMessage(
                subject, message, to=[email]
            )
            email.content_subtype = 'html'
            email.send()
            return redirect('user:verify-email-done')
        else:
            return redirect('user:signup')
    
    return render(request, 'accounts/verify-email.html')


def verify_email_done(request):
    return render(request, 'accounts/verify-email-done.html')


def verify_email_confirm(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    
    if user is not None and account_activation_token.check_token(user, token):
        user.email_is_verified = True
        user.save()
        messages.success(request, "Votre adresse email a été vérifié avec succès.")
        return redirect('user:verify-email-complete')
    else:
        messages.warning(request, "Le lien est invalide.")
        
    return render(request, "accounts/verify-email-confirm.html")


def verify_email_complete(request):
    return render(request, 'accounts/verify-email-complete.html')        

def signup_view(request):
    template_name = 'accounts/signup.html'
    if request.method == 'POST':
        next = request.GET.get('next')
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            password = form.cleaned_data.get('password')
            user.save()
            new_user = authenticate(email=user.email, password=password)
            login(request, new_user)
            if next:
                return redirect(next)
            else:
                return redirect('verify-email')
            
    else:
        form = UserRegisterForm()
        
    context = {
        'form': form,
    }
    return render(request, template_name, context)

accounts/templates/accounts/home.html
<h3>Bienvenu {{name}}</h3>
<hr>
<p>{{domains}}</p>

accounts/templates/accounts/signup.html
{% load widget_tweaks %}

{% if form.non_field_errors %}
    {% for message in form.non_field_errors %}
        {{ message }}
    {% endfor %}
{% endif %}

<form method="post">
    {% csrf_token %}
    <div>
        <label for="email">Email</label>
        {% render_field form.email %}       
    </div>
    <div>
        <label for="password">Password</label>
        {% render_field form.password %}
    </div>
    

    <button type="submit">Valider</button>
</form>

accounts/templates/accounts/verify-email-complete.html
<div class="alert alert-success">
    Votre adresse e-mail a été vérifiée avec succès.
</div>

accounts/templates/accounts/verify-email-confirm.html
<div class="container">
    {% if messages %}
        {% for message in messages %}
            <div class="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
</div>

accounts/templates/accounts/verify-email-done.html
<h3>
    Un email a été envoyé avec les instructions 
    pour la vérification de votre adresse email.
</h3>

accounts/templates/accounts/verify-email-message.html
<div style="background-color: #c2c2c2; padding: 15px;">
    <h2 style="margin: 0; padding: 10px; border-top-left-radius: 10px; border-top-right-radius: 10px; background-color: #5865F2; color: #ffffff;">Verification Email</h2>
    <div style="margin: 0; padding: 15px; background-color: #ffffff;">
        <p>Hi {{ user.name }},</p>
        <p>Vous avez créé un compte sur {{ domain }}, veuillez cliquer sur le lien ci-dessous pour valider votre inscription.</p>
        <a href="{{ request.scheme }}://{{ domain }}{% url 'user:verify-email-confirm' uidb64=uid token=token %}" style="border: 0; color: #ffffff; background-color: #5865F2; padding: 15px; font-weight: bold; text-decoration: none; border-radius: 5px;">
            Verifier votre adresse e-mail
        </a>
        <p style="margin-top: 40px;">Ou vous pouvez copier le lien ci-dessous dans le navigateur</p>
        <p>{{ request.scheme }}://{{ domain }}{% url 'user:verify-email-confirm' uidb64=uid token=token %}</p>
        <p>L'équipe de Digitalux</p>
    </div>
    
</div>

accounts/templates/accounts/verify-email.html
<h1>Veuillez vérifier votre email</h1>
<form method="post">
    {% csrf_token %}
    <input class="btn btn-primary max-btn" type="submit" value="Verifier">
</form>